# Generated by Django 3.2 on 2021-05-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slack_user_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
