# Generated by Django 3.2 on 2021-05-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumeal',
            name='available_on',
        ),
    ]
