# Generated by Django 3.2 on 2021-05-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_menumeal_available_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menumeal',
            unique_together={('meal', 'menu')},
        ),
    ]
