name: Test Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Django Coverage action
        uses: actions/python-django-coverage-gitHub-action@0.9
        with:
          django-app: 'backend_test'
          minimum-coverage: '80'
